### ISSUE TITLE
Conflict with Collective

### ISSUE THREAD

**Issue by Archimage1** [infernalstudios/Sortilege#16]
Crashed on startup with an error stating -

```
Collective (collective) has failed to load correctly
java.lang.ExceptionInInitializerError: null
```

I created a new pack with only -

Minecraft 1.19.2
Forge 43.4.5
Sortilege 1.5.4
Collective 7.64

and was able to duplicate the error.  Collective is a library mod by Serilum.  There seems to be a problem with the registration of limitite.

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-11-10 21:09:13
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.4.5-universal.jar%23136!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.4.5-universal.jar%23136!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.5.jar%23126!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc5.jar:mmc5] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:336) ~[?:?] {}
-- MOD collective --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at net.minecraft.world.item.ItemStack.handler$zzf000$enchant(ItemStack.java:1100) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:sortilege.mixins.json:MixinItemStack,pl:mixin:A}
		at net.minecraft.world.item.ItemStack.m_41663_(ItemStack.java) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:sortilege.mixins.json:MixinItemStack,pl:mixin:A}
		at com.natamus.collective_common_forge.data.Constants.initConstantData(Constants.java:26) ~[collective-1.19.2-7.64.jar%23129!/:?] {re:classloading}
		at com.natamus.collective_common_forge.CollectiveCommon.init(CollectiveCommon.java:13) ~[collective-1.19.2-7.64.jar%23129!/:?] {re:classloading}
		at com.natamus.collective.CollectiveForge.<init>(CollectiveForge.java:32) ~[collective-1.19.2-7.64.jar%23129!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[javafmllanguage-1.19.2-43.4.5.jar%23133!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.4.5.jar%23132!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /home/david/.UltimMC/instances/Test/.minecraft/mods/collective-1.19.2-7.64.jar
	Failure message: Collective (collective) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 7.64
	Mod Issue URL: https://github.com/Serilum/.issue-tracker/labels/Library:%20Collective
	Exception message: java.lang.NullPointerException: Registry Object not present: sortilege:limitite
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:336) ~[?:?] {}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.4.5-universal.jar%23136!/:?] {re:mixin,re:classloading}
	at net.lyof.sortilege.utils.ItemHelper.<clinit>(ItemHelper.java:21) ~[Sortilege-1.19.2-1.5.4.jar%23130!/:1.0] {re:mixin,re:classloading}
	at net.minecraft.world.item.ItemStack.handler$zzf000$enchant(ItemStack.java:1100) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:sortilege.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41663_(ItemStack.java) ~[client-1.19.2-20220805.130853-srg.jar%23131!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:sortilege.mixins.json:MixinItemStack,pl:mixin:A}
	at com.natamus.collective_common_forge.data.Constants.initConstantData(Constants.java:26) ~[collective-1.19.2-7.64.jar%23129!/:?] {re:classloading}
	at com.natamus.collective_common_forge.CollectiveCommon.init(CollectiveCommon.java:13) ~[collective-1.19.2-7.64.jar%23129!/:?] {re:classloading}
	at com.natamus.collective.CollectiveForge.<init>(CollectiveForge.java:32) ~[collective-1.19.2-7.64.jar%23129!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[javafmllanguage-1.19.2-43.4.5.jar%23133!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.4.5.jar%23132!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.8.0-48-generic
	Java Version: 17.0.12, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 816941896 bytes (779 MiB) / 1409286144 bytes (1344 MiB) up to 8992587776 bytes (8576 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-8320 Eight-Core Processor
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: Piledriver
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: GF108 [GeForce GT 530]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 160.00
	Graphics card #0 deviceId: 0x0de5
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10041.66
	Virtual memory used (MB): 6437.29
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 931.02
	JVM Flags: 2 total; -Xms128m -Xmx8576m
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.4.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.4.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.4.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.4.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.4.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Sortilege-1.19.2-1.5.4.jar                        |Sortilege                     |sortilege                     |1.5.4               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.4.5-universal.jar                 |Forge                         |forge                         |43.4.5              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		collective-1.19.2-7.64.jar                        |Collective                    |collective                    |7.64                |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: c2b81892-0f23-4012-834f-c9b6e5a310ea
	FML: 43.4
	Forge: net.minecraftforge:43.4.5
```

**Comment by Archimage1** [comment]
Thanks for the response.  Glad it's already taken care of.  I'll watch for the next release.
